[alembic]
script_location = %(here)s/src/bookreviews/adapters/migrations
file_template = %%(rev)s_%%(slug)s

[post_write_hooks]
hooks = ruff_check, ruff_format
ruff_check.type = exec
ruff_check.executable = ruff
ruff_check.options = check --fix --quiet REVISION_SCRIPT_FILENAME
ruff_format.type = exec
ruff_format.executable = ruff
ruff_format.options = format --quiet REVISION_SCRIPT_FILENAME
