apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookreviews

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/eleuname-dev/progetto-go/bookreviews
    newTag: main

configMapGenerator:
  - name: bookreviews-config
    behavior: merge
    literals:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector.monitoring:4318
      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      - OTEL_TRACES_SAMPLER_ARG=0.1

patches:
  - target:
      kind: HTTPRoute
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: reviews.example.com
      - op: add
        path: /spec/parentRefs/0/namespace
        value: gateway-system
      - op: replace
        path: /spec/parentRefs/0/name
        value: public
  - target:
      kind: Deployment
      name: bookreviews-worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
